amcl:
  ros__parameters:
    use_sim_time: True
    max_particles: 2000
    min_particles: 500

local_costmap:
  ros__parameters:
    resolution: 0.05
    robot_radius: 0.2
    obstacle_range: 2.5
    inflation_radius: 0.6

global_costmap:
  ros__parameters:
    resolution: 0.05
    obstacle_range: 2.5
    inflation_radius: 0.6
