slam_toolbox:
  map_file_name: "map.pgm"
  resolution: 0.05
  publish_frequency: 1.0
  laser_scan_topic: "/scan"
  max_laser_range: 20.0
  minimum_time_between_pose_updates: 0.5
  slam_mode: "online_async"
